---
title: "R Notebook"
output: html_notebook
---

# Analysis of Deropapy behaviour (sensibility tests)

```{r, LoadLibs}
library("data.table")
library("RSQLite")
library("tidyverse")
library("plotly")
library("GGally")
```

# Find db to be used
```{r}
# working wit develop base sim for now
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()

thisOutPath <- file.path(getwd(),"outputs")
thisOutPath
```

```{r}
# 1. Find files
dbFileList <- list.files(pattern='Deropapy.db$', full.names = TRUE,include.dirs = FALSE,no..= FALSE)
print(dbFileList)
```
Function to get data from db

```{r}

# 2. Extract data
GetApsimNGTable <- function(dbLoc, table) 
{
  connection <- dbConnect(SQLite(), dbname = dbLoc, flags = SQLITE_RW) #The connection to the database
  table <- dbReadTable(connection, table, row.names=NULL) # The data in a table
  dbDisconnect(connection)
  return(table)
}
```

# Get data
```{r}
info_out_raw <- data.table()
list_of_dts <- list()

# which table to extract?
#TableName <- "ReportSensitivity" # annual outputs
TableName <- c("Output") # annual outputs

for (i in 1:length(TableName)) {
  
  db.name <- dbFileList
  
  db.full.path <- file.path(db.name)
  
  # connect to the SQLite db file    
  con <- dbConnect(SQLite(), dbname = db.full.path, flags = SQLITE_RW)
  
  # get a list of all tables from db
  alltables <- dbListTables(con)
  alltables
  dbDisconnect(con)
  #gc()
  
  # get table as a `data.frame`
  temp1 <- data.table()
  temp1 <- GetApsimNGTable(db.full.path, TableName[i])
  
 # info_out_raw <- rbind(info_out_raw, temp1)
  
  list_of_dts[[i]] <- temp1
  
}

#summary(info_out_raw)
summary(list_of_dts)
list_of_dts[[1]]
```
# Create formated version of data
```{r}

# columns as factor 
columns_as_factors <- c("Experiment","Crop","Location",
                        "Irrigation","GCM","RCP","TimeSlice","SoilStamp", 
                        "Lat", "Lon", "Zone", "AGENT_NO", "MGMT","SoilType")

# get met summary by location

# prepare work df
info_out_work <- list_of_dts[[1]] %>% 
  # align Edith's and Xiumei's sensitivity nomenclature
  mutate(MGMT = factor(ifelse(is.na(MGMT),"Basic",MGMT))) %>%
  mutate(
    Irrigation = case_when(
      is.na(Irrigation) & MGMT == "Basic" ~ "Rainfed",
      is.na(Irrigation) & MGMT == "FF" ~ "Rainfed",
      is.na(Irrigation) & MGMT == "Irrig" ~ "Irrigated",
      is.na(Irrigation) & MGMT == "FFandIrrig" ~ "Irrigated",
      TRUE ~ Irrigation # Keep existing values
    )) %>%
  mutate(across(all_of(columns_as_factors), factor))%>%
  mutate(ReportDate=as.Date(ymd_hms(ReportDate)))%>%
  mutate(SoilType=factor(SoilType,
                      levels=c("DeepStonySandGeneric",
                               "VeryDeepHeavySiltLoamGeneric"), 
                      labels=c("Sandy",
                               "Silty")))%>%
  filter(str_detect(Experiment, "Testing|Sensitivity")) # select sens runs only
  

summary(info_out_work)

unique(info_out_work$Location)
```

# set crops
```{r}
thisCropPerennials <- c("Grapevine","Avocado","Macadamia","Lemon")
thisCropAnnuals <- c("Maize","Wheat","Hemp","OSR")
seleted_yield_columns <- c("ProductFresh_kgPerHa")
```


# Add a latitude column to order locations
```{r}
# Sample data frame (replace with your actual data)
df_lat_reg_raw <- data.frame(Location = c("Canterbury", "CentralOtago", "Gisborne", "Southland", 
                              "Northland", "Waikato", "HawkesBay", "Marlbrough", 
                              "KeriKeri", "Wharerangi", "Te Puke", "Auckland"))

# Add average latitude based on location
df_lat_reg_work <- df_lat_reg_raw %>%
  mutate(Latitude = case_when(
    Location == "Canterbury"   ~ -43.5,
    Location == "CentralOtago" ~ -45.0,
    Location == "Gisborne"     ~ -38.7,
    Location == "Southland"    ~ -46.4,
    Location == "Northland"    ~ -35.5,
    Location == "Waikato"      ~ -38.0,
    Location == "HawkesBay"    ~ -39.6,
    Location == "Marlbrough"   ~ -41.7,
    Location == "KeriKeri"     ~ -35.2,
    Location == "Wharerangi"   ~ -39.5,
    Location == "Te Puke"      ~ -37.8,
    Location == "Auckland"     ~ -36.8,
    TRUE ~ NA_real_  # Default if no match
  ))


head(df_lat_reg_work)
```


# Create subset of results
```{r, fig.height=14}

# get met summary
thisMetPath <- file.path(getwd(),"MetFiles")

met_summary_by_AGNO <- 
  read.csv2(file.path(thisMetPath,
                      "summarised_met_data.csv"),
                       sep=",") %>%
  mutate(AGENT_NO=factor(AGENT_NO))


# 
info_out_work_subset <- info_out_work %>%
  dplyr::filter(Crop %in% c(thisCropAnnuals,thisCropPerennials))  %>%
  dplyr::select(columns_as_factors, seleted_yield_columns, "Year")  %>%
  dplyr::mutate(RCP = "Baseline", RCP=factor(RCP)) %>% # climate files from ERA were used 
  inner_join(met_summary_by_AGNO, by="Location") %>%
    inner_join(df_lat_reg_work, by="Location") %>%
  mutate(Location=factor(Location),
         Location2= factor(paste0(Location," (",Latitude,"o)\n", 
                                  "(", meant,"oC | ",
                                  rain," mm/year | ",
                                  radn," MJ/m2)"))) 


summary(info_out_work_subset)
```

```{r, fig.height=14}
info_out_work_subset %>%
  tidyr::gather(VarName,VarValue, seleted_yield_columns) %>%
  ggplot(aes(x=Irrigation,y=VarValue, colour=SoilType)) +
  geom_boxplot() +
  geom_point(position = position_dodge(width = 0.75)) +
  facet_wrap(Crop~VarName, scales="free")
```





```{r, fig.height=6}
all_crops <- c(thisCropPerennials,thisCropAnnuals)

for (i in 1:length(all_crops)) {
  
thisCrop <- all_crops[i]

print(thisCrop)

g <- info_out_work_subset %>%
  filter(Crop == thisCrop) %>%
  mutate(Location2 = fct_reorder(Location2, Latitude))%>%
  filter(MGMT %in% c("Basic","Irrig")) %>%
  tidyr::gather(VarName, VarValue, seleted_yield_columns) %>%
  ggplot(aes(x = Location2, y = VarValue,fill = SoilType,colour = SoilType)) +
  geom_violin(position = position_dodge(0.75), 
              alpha = 0.2) +  # Violin color & aligned
  geom_boxplot(position = position_dodge(0.75), outlier.shape = NA, alpha = 0.2) +  
  geom_point(position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.75), 
             size = 2, alpha = 0.5) +
  facet_grid(Crop ~ Irrigation, scales = "free") +
  scale_y_continuous(limits = c(0, NA)) +
  coord_flip()+
  ylab("Productivity (kg/ha)") +
  xlab("Location") +
  theme(text = element_text(size = 14))


print(g)

ggsave(filename = 
       file.path(thisOutPath, "Graphs",paste0("Sensitivity_",thisCrop,".jpg")),
       plot = g,
       dpi = 300)

}
```
Summary stats
```{r}

# Check values by changing crop name

theCrop <- "Macadamia" 
# "Grapevine" "Avocado" "Macadamia" "Lemon" 
# "Maize" "Wheat" "Hemp" "OSR"

info_out_work %>%
  filter(Crop==theCrop) %>%
  group_by(Crop, Location) %>%
  summarise(Min=min(ProductFresh_kgPerHa), 
            Med=median(ProductFresh_kgPerHa), 
            Max=max(ProductFresh_kgPerHa))
```
Summary stats
```{r, fig.height=12}

# Choose crop to analyse below

theCrop <- "Hemp" 
# "Grapevine" "Avocado" "Macadamia" "Lemon" 
# "Maize" "Wheat" "Hemp" "OSR"

info_out_work %>%
  tidyr::gather(VarName,VarValue,Es_Cum:FrostSeverity) %>%
  filter(Crop==theCrop) %>%
  #filter(Location=="Auckland") %>%
  #filter(SoilType=="Sandy") %>%
  #filter(SoilType=="Silty") %>%
  ggplot(aes(x=VarValue, y=ProductFresh_kgPerHa,
             linetype=interaction(Irrigation, SoilType))) +
  geom_point(aes(colour=Location, shape=Irrigation)) +
 # stat_summary(fun.data= info_out_work) + 
  geom_smooth(method='lm') +
  facet_wrap(VarName~., scales="free") +
  ylim(0, NA)
```
```{r}
info_out_work %>% 
  #filter(Crop == "Hemp") %>%
  ggplot(aes(x=AboveGround_kgPerHa/1000, y=ProductFresh_kgPerHa/1000, colour=SoilType)) +
  geom_point(alpha=0.2, size=1.5)+
  facet_wrap(Crop~Irrigation)+  # Scatter plot points
  geom_abline(slope = 0.5, intercept = 0, color = "black", linetype = "dashed") 
```
# Check Harvest Index variability

```{r, fig.height=14}
info_out_work %>% 
 # filter(Crop=="Wheat") %>%
  tidyr::gather(VarName,VarValue,AboveGround_kgPerHa,ProductFresh_kgPerHa)%>%
  ggplot(aes(x=Irrigation,y=VarValue/1000)) +
  geom_boxplot(alpha=0.2) +
  geom_violin(alpha=0.2) +
  geom_jitter(alpha =0.2, width=0.1) +
  facet_wrap(Crop~VarName, ncol=4, scales='free')  +
  coord_flip() +
  theme(text = element_text(size = 14)) 
```










